test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID:    AYbK8OavdjZSCpZXb0kTIfiM4ZZosgZpbnRbbXAOS0fmd1iUcbQudIYoi4DEikODllbDaeZGrjES964x
  PAYPAL_CLIENT_SECRET:  EBUF8FiBehcOQnJFr-uCn3BUOgsH8ZgiGHv121GAOgd8kdNoJD-UbrNre3mmDNxRvJuCJbNuuqXL9CNh
  STRIPE_PUBLISHABLE_KEY: pk_test_51Kgo2rSIe5lxnQTveJ2HbQtaiD8Q0zsGFaM1fMGa2v7TBn2AWfqN7HuGE6zOsZdFjvJNcyLuskaXfQIQhm0GBIB700wGIso0iz
  STRIPE_SECRET_KEY:  sk_test_51Kgo2rSIe5lxnQTvewjfQJxpDF2FQMQdr3JDvZew1eKf3sPZGlJc3YiF8OwVo9Fo4fTrgJOA7BpEEjyF5mDMgX8V00xhWcmw9q
development:
  <<: *default
